syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.io.begstd.slot.grpc.slotgame";

service HelperService {
    rpc getActivePlayers(ActivePlayerRequest) returns (ActivePlayerResponse) {};
    rpc getServiceGameConfig(ServiceGameConfigRequest) returns (ServiceGameConfigResponse) {};
    rpc getServiceProperty(ServicePropertyRequest) returns (ServicePropertyResponse) {};
    rpc getTotalActivePlayers(GetTotalActivePlayersReq) returns (GetTotalActivePlayersResp);
}

message ActivePlayerRequest {
}

message ActivePlayerResponse {
    repeated ActivePlayerSG activePlayers = 1;
}

message ActivePlayerSG {
    string playerId = 1;
    int32 status = 2;
}

message ServiceGameConfigRequest {

}

message ServiceGameConfigResponse {
    string config = 1;
}

message ServicePropertyRequest {

}

message ServicePropertyResponse {
    string property = 1;
}

message GetTotalActivePlayersReq {
}

message GetTotalActivePlayersResp {
    int32 totalUsers = 1;
    int32 totalBots = 2;
}
