syntax = "proto3";

import "google/protobuf/struct.proto";
import "promotion-service.proto";
option java_multiple_files = true;
option java_package = "com.io.begstd.slot.grpc.slotgame";

service SlotGameService {
    rpc normalSpin (NormalSpin) returns (ResponseStatusSG) {};
    rpc freeSpin (FreeSpin) returns (ResponseStatusSG) {};
    rpc respin (FreeSpin) returns (ResponseStatusSG) {};
    rpc miniGame (MiniGame) returns (ResponseStatusSG) {};
    rpc freeSpinOption (FreeSpinOption) returns (ResponseStatusSG) {};

    rpc joinGame(PlayerInfo) returns (ResponseStatusSG) {};
    rpc joinGameEvent(PlayerEventInfo) returns (ResponseStatusSG) {};
    rpc leaveGame(PlayerInfo) returns (ResponseStatusSG) {};
    rpc gamble(GambleBet) returns (ResponseStatusSG) {};
    rpc lightningSpin (LightningSpin) returns (ResponseStatusSG) {};
    rpc powerUpSpin (PowerUpSpin) returns (ResponseStatusSG) {};

    rpc joinGameTrial(PlayerTrialInfo) returns (ResponseStatusSG) {};
    rpc normalSpinTrial (NormalSpin) returns (ResponseStatusSG) {};
    rpc freeSpinTrial (FreeSpin) returns (ResponseStatusSG) {};
    rpc respinTrial (FreeSpin) returns (ResponseStatusSG) {};
    rpc miniGameTrial (MiniGame) returns (ResponseStatusSG) {};
    rpc freeSpinOptionTrial (FreeSpinOption) returns (ResponseStatusSG) {};
    rpc gambleTrial(GambleBet) returns (ResponseStatusSG) {};
    rpc lightningSpinTrial (LightningSpin) returns (ResponseStatusSG) {};
    rpc powerUpSpinTrial (PowerUpSpin) returns (ResponseStatusSG) {};

    rpc getLatestState (GetLatestStateRequest) returns (ResponseStatusSG){};
    rpc setGroupUsersMaintain (GroupUsersMaintainRequest) returns (ResponseStatusSGBO) {};
    rpc updateUserLevel (UserLevelRequest) returns (ResponseStatusSGBO) {};

    rpc playerActive(PlayerActiveRequest) returns (ResponseStatusSG) {};
    rpc gltEvent(GltEventInfo) returns (ResponseStatusSG) {};


    rpc vsNormalSpin (VSNormalSpin) returns (ResponseStatusSG) {};
    rpc vsGetPayout (VSPayoutReq) returns (ResponseStatusSG) {};

    rpc joinLobby(PlayerInfo) returns (ResponseStatusSG) {};
    rpc joinTable(PlayerTableInfo) returns (ResponseStatusSG) {};
    rpc leaveTable(PlayerTableInfo) returns (ResponseStatusSG) {};
    rpc normalSpinTable (NormalSpin) returns (ResponseStatusSG) {};
    rpc freeSpinTable (FreeSpin) returns (ResponseStatusSG) {};
    rpc respinTable (FreeSpin) returns (ResponseStatusSG) {};
    rpc miniGameTable (MiniGame) returns (ResponseStatusSG) {};
    rpc freeSpinOptionTable (FreeSpinOption) returns (ResponseStatusSG) {};

    rpc leaveGameTrial(PlayerInfo) returns (ResponseStatusSG) {};
}

message ExtensionReloadRequest {
    repeated string sourceFiles = 1;
    repeated ExtensionModel extensionModels = 2 ;
}

message ExtensionModel {
    string type = 1;
    repeated string qualifyNames = 2;
}

message PlayerTrialInfo {
    string sId = 1;
    string uId = 2;
    string cId = 3;
    UserJoinGameDetail ud = 16;
    int32 env = 17;
    string ssid = 18;
}

message GambleBet{
    string uId = 1;
    string cId = 2;
    int32 cOp = 3;
    double talB = 4;
    UserJoinGameDetail ud = 16;
    int32 env = 17;
    string ssid = 18;
}

message PlayerInfo {
    string sId = 1;
    string uId = 2;
    string cId = 3;
    int32 env = 4;
    PromotionData promotionData = 5;
    UserJoinGameDetail ud = 16;
    string c = 17;
    string ssid = 18;
}

message PlayerEventInfo {
    string sId = 1;
    string uId = 2;
    string cId = 3;
    int32 env = 4;
    UserJoinGameDetail ud = 16;
    string c = 17;
    string eId = 18;
    string ssid = 19;
}

message PlayerTableInfo {
    string sId = 1;
    string uId = 2;
    string cId = 3;
    int32 env = 4;
    UserJoinGameDetail ud = 16;
    string c = 17;
    int32 tbId = 18;
    string ssid = 19;
}

message NormalSpin {
    string uId = 1;
    string cId = 2;
    string bId = 3;
    double talB = 16;
    repeated int32 bLn = 17;
    UserJoinGameDetail ud = 18;
    int32 wo = 19;
    int32 env = 20;
    string ssid = 21;
    repeated int32 opts = 22;
    string l = 23;
}

message FreeSpin {
    string uId = 1;
    string cId = 2;
    UserJoinGameDetail ud = 16;
    int32 env = 17;
    string ssid = 18;
    repeated int32 opts = 19;
}

message MiniGame {
    string uId = 1;
    string cId = 2;
    int32 cOp = 3;
    UserJoinGameDetail ud = 16;
    int32 env = 17;
    string ssid = 18;
}

message LightningSpin {
    string uId = 1;
    string cId = 2;
    int32 opt = 3;
    UserJoinGameDetail ud = 16;
    int32 env = 17;
    string ssid = 18;
}

message PowerUpSpin {
    string uId = 1;
    string cId = 2;
    int32 cOp = 3;
    UserJoinGameDetail ud = 16;
    int32 env = 17;
    string ssid = 18;
}

message GetLatestStateRequest {
    string cId = 1;
    string uId = 2;
    UserJoinGameDetail ud = 16;
}

message ResponseStatusSG {
    string c = 1;
    google.protobuf.Struct st = 2;
}

message ResponseStatusSGBO {
    string code = 1;
    google.protobuf.Struct state = 2;
}

message FreeSpinOption {
    string uId = 1;
    string cId = 2;
    int32 opt = 3;
    UserJoinGameDetail ud = 16;
    int32 env = 17;
    string ssid = 18;
}

message UserJoinGameDetail {
    double money = 1;
    double extraMoney = 2;
    string displayName = 3;
    string fullname = 4;
    string email = 5;
    string phone = 6;
    string address = 7;
    string birthday = 8;
    string country = 9;
    string gender = 10;
    string avatar = 11;
    string registerIp = 12;
    string ip = 13;
    string os = 14;
    string device = 15;
    string browser = 16;
    repeated string denyGameIds = 17;
    string userType = 18;
    string userAgent = 19;
    string agencyId = 20;
    string memberId = 21;
    string externalId = 22;
    string userBrand = 23;
    string level = 24;
    repeated WALLET_TYPE walletType = 25;
    string currency = 26;
}

message GroupUsersMaintainRequest {
    bool maintain = 1;
    string prefix = 2;
}

message UserLevelRequest {
    string userId = 1;
    string level = 2;
}

message ExtensionClass {
    string type = 1;
    repeated string qualifyNames = 2;
}

message PlayerActiveRequest {
    string cId = 1;
    string uId = 2;
}

message GltEventInfo {
    string uId = 1;
    string cId = 2;
    UserJoinGameDetail ud = 16;
}

enum WALLET_TYPE {
    MAIN_BALANCE = 0;
    PROMOTION_BALANCE = 1;
}

message VSNormalSpin {
    string uId = 1;
    string cId = 2;
    string bId = 3;
    repeated string bLns = 16;
    UserJoinGameDetail ud = 17;
    int32 wo = 18;
    int32 env = 19;
    string ssid = 20;
    int32 mo = 21;
    string gn = 22;
}

message VSPayoutReq {
    string uId = 1;
    string cId = 2;
    int32 cOp = 3;
    UserJoinGameDetail ud = 16;
}
