#TOMCAT SERVER PORT
server:
  port: 8090
  servlet:
    context-path: /9000

service:
  startTest: true
  enableKafka: false
  intervalCheckStartTestSeconds: 600
  maxSizeQueue: 100
  externalServiceType:
    jackpotService: test
    walletService: test
    playViewStoreService: test
    promotionService: test
  internalServiceType:
    commandIdHistory: test
    joingame: test
    walletTrialModeService: test
    jackpotTrialModeService: test
    rtpConfigService: test
spring:
  kafka:
    template:
      default-topic: logger001
      bot-topic: bot-logger001
      partition: 3
    bootstrap-servers: 127.0.0.1:9092
    enviromentType: prod
