rtp:
  data:
    userPrefix: testuser
    gameId: 9999
    serviceId: 9999
    commandId: rtp
    needJoinGame: false
    minigame.size: 15
thread:
  corePoolSize: 7
  maxPoolSize: 16
service:
  startTest: false
  intervalCheckStartTestSeconds: 600
  externalServiceType:
    jackpotService: test
    walletService: test
    playViewStoreService: test
    promotionService: test
  internalServiceType:
    joingame: test
    walletTrialModeService: test
    jackpotTrialModeService: test
    rtpConfigService: prod
