syntax = "proto3";

import "google/protobuf/struct.proto";
option java_multiple_files = true;
option java_package = "com.io.begstd.dice.grpc.promotiongame";

service PromotionDiceGameService {
    rpc updateUserPromotion(UpdateUserPromotionDiceGameRequest) returns (PromotionDiceGameResponse);
}

message UpdateUserPromotionDiceGameRequest {
    repeated PromotionDiceGameData listPromotionData = 1;
}

message PromotionDiceGameData {
    string userId = 1;
    string promotionCode = 2;
    string promitionName = 3;
    bool   isValid = 4;
    int64 expireAt = 5;
    string type = 6; // 'new': user has added new promotion, 'reset': for daily reset.
    google.protobuf.Struct data = 7; // {betid: 10, remain: 5, total: 5}
    string curr = 8;
}

message PromotionDiceGameResponse {
    int32 code = 1; // status of response, 0 for success
    string message = 2; // message to describe the code above.
}
